<?php

use Flarum\Extend;
use Local\Brand\Head;

/**
 * The identity of Looksmax.lat.
 *
 * Owns the mark, the lockup, the icon set, the share cards, the colour and the
 * document head. Loaded on both frontends because the admin panel is part of
 * the product: an admin who logs in to a stock Flarum chrome has been handed a
 * different piece of software than the one their members see.
 *
 * brand.less is generated by tools/palette.py and is loaded first, so every
 * --brand-* custom property is defined before anything consumes it. It is
 * deliberately a separate file from the rules that use it: other extensions in
 * this stack are expected to consume the tokens, and a token file that also
 * carries opinions is one that cannot be adopted.
 */
return [
    (new Extend\Frontend('forum'))
        ->css(__DIR__.'/less/brand.less')
        ->css(__DIR__.'/less/forum.less')
        ->content(Head::class),

    (new Extend\Frontend('admin'))
        ->css(__DIR__.'/less/brand.less')
        ->css(__DIR__.'/less/admin.less'),

    // The server-rendered pages: 404, 500, CSRF mismatch, password reset,
    // e-mail confirmation, log-out. These render with no extension stylesheet
    // at all — core's layouts/basic.blade.php is a white page with #333 text
    // and inline CSS — so they cannot be reached from LESS. extendNamespace
    // *prepends* our hint path (Extend/View.php:60-64), so a file of the same
    // name here wins over core's without patching vendor.
    (new Extend\View())
        ->extendNamespace('flarum.forum', __DIR__.'/views'),

    // Exposed to the frontend so a client-side surface (the loading state, a
    // share button, an embed) can reach the brand without hardcoding a path,
    // and so the share image can be pointed elsewhere without a deploy.
    (new Extend\Settings())
        ->serializeToForum('brand.assets', 'brand.assets', null, 'assets/extensions/local-looksmax-brand')
        ->serializeToForum('brand.ogImage', 'brand.og_image'),

    // The 404/500 pages and the share-card alt text. These render server-side
    // with no frontend bundle, so the translations have to be resolved in PHP.
    (new Extend\Locales(__DIR__.'/locale')),
];
